package HOBACITv2.generator.templates;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.impl.query.QueryProviderBase;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.core.behavior.INamedConcept__BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import java.util.Map;
import jetbrains.mps.generator.impl.query.SourceNodesQuery;
import java.util.HashMap;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.impl.query.QueryKey;
import java.util.Collection;
import jetbrains.mps.generator.impl.GenerationFailureException;
import jetbrains.mps.util.IterableUtil;
import jetbrains.mps.generator.impl.query.PropertyValueQuery;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;

@Generated
public class QueriesGenerated extends QueryProviderBase {
  public QueriesGenerated() {
    super(1);
  }
  public static Object propertyMacro_GetValue_1_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.matchId$v8bY);
  }
  public static Object propertyMacro_GetValue_1_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.dataType$nnY);
  }
  public static Object propertyMacro_GetValue_1_2(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.attributeid$Xd30);
  }
  public static Object propertyMacro_GetValue_1_3(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.catogory$cvsA);
  }
  public static Object propertyMacro_GetValue_1_4(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.dataType$B160);
  }
  public static Object propertyMacro_GetValue_1_5(final PropertyMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), PROPS.mustBePresent$a_mo);
  }
  public static Object propertyMacro_GetValue_1_6(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.ruleid$paNZ);
  }
  public static Object propertyMacro_GetValue_1_7(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.functionId$J5WM);
  }
  public static Object propertyMacro_GetValue_1_8(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.dataType$nnY);
  }
  public static Object propertyMacro_GetValue_1_9(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.attributeid$Xd30);
  }
  public static Object propertyMacro_GetValue_1_10(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.catogory$cvsA);
  }
  public static Object propertyMacro_GetValue_1_11(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.dataType$B160);
  }
  public static Object propertyMacro_GetValue_1_12(final PropertyMacroContext _context) {
    return (String) INamedConcept__BehaviorDescriptor.getFqName_idhEwIO9y.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_13(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.policyid$TmVT);
  }
  public static Object propertyMacro_GetValue_1_14(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.ruleCombiningAlgId$rL3l);
  }
  public static Object propertyMacro_GetValue_1_15(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.version$mVA$);
  }
  public static Object propertyMacro_GetValue_1_16(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Iterable<SNode> sourceNodesQuery_1_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.attrV$AmLZ);
  }
  public static Iterable<SNode> sourceNodesQuery_1_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.designV$FJoi);
  }
  public static Iterable<SNode> sourceNodesQuery_1_2(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.match$C54c);
  }
  public static Iterable<SNode> sourceNodesQuery_1_3(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.allof$n99Y);
  }
  public static Iterable<SNode> sourceNodesQuery_1_4(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.anyof$6O2d);
  }
  public static Iterable<SNode> sourceNodesQuery_1_5(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attributeValue$t8Ga);
  }
  public static Iterable<SNode> sourceNodesQuery_1_6(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.designator$NOtP);
  }
  public static Iterable<SNode> sourceNodesQuery_1_7(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.apply$dHjv);
  }
  public static Iterable<SNode> sourceNodesQuery_1_8(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.condition$Kgk);
  }
  public static Iterable<SNode> sourceNodesQuery_1_9(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.rules$A0S);
  }
  private final Map<String, SourceNodesQuery> snsqMethods = new HashMap<String, SourceNodesQuery>();
  {
    int i = 0;
    snsqMethods.put("3951418197005218390", new SNsQ(i++));
    snsqMethods.put("3951418197005219698", new SNsQ(i++));
    snsqMethods.put("3951418197005206017", new SNsQ(i++));
    snsqMethods.put("3951418197005204605", new SNsQ(i++));
    snsqMethods.put("3951418197005193442", new SNsQ(i++));
    snsqMethods.put("3951418197004795137", new SNsQ(i++));
    snsqMethods.put("3951418197004894198", new SNsQ(i++));
    snsqMethods.put("3951418197004782720", new SNsQ(i++));
    snsqMethods.put("3951418197004775767", new SNsQ(i++));
    snsqMethods.put("3951418197004707667", new SNsQ(i++));
  }
  @NotNull
  @Override
  public SourceNodesQuery getSourceNodesQuery(@NotNull QueryKey identity) {
    SourceNodesQuery query = identity.forFunctionNode(snsqMethods);
    return (query != null ? query : super.getSourceNodesQuery(identity));
  }
  private static class SNsQ implements SourceNodesQuery {
    private final int methodKey;
    public SNsQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @NotNull
    public Collection<SNode> evaluate(@NotNull SourceSubstituteMacroNodesContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_0(ctx));
        case 1:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_1(ctx));
        case 2:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_2(ctx));
        case 3:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_3(ctx));
        case 4:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_4(ctx));
        case 5:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_5(ctx));
        case 6:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_6(ctx));
        case 7:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_7(ctx));
        case 8:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_8(ctx));
        case 9:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_9(ctx));
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, PropertyValueQuery> pvqMethods = new HashMap<String, PropertyValueQuery>();
  {
    int i = 0;
    pvqMethods.put("3951418197005209517", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "id"));
    pvqMethods.put("3951418197005247924", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "data"));
    pvqMethods.put("3951418197005255797", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "id"));
    pvqMethods.put("3951418197005267262", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "category"));
    pvqMethods.put("3951418197005280495", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "data"));
    pvqMethods.put("3951418197005295460", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "result"));
    pvqMethods.put("3951418197004715403", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "id"));
    pvqMethods.put("3951418197004789276", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "id"));
    pvqMethods.put("3951418197004821350", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "data"));
    pvqMethods.put("3951418197004924361", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "id"));
    pvqMethods.put("3951418197004928490", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "text"));
    pvqMethods.put("3951418197004932656", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "data"));
    pvqMethods.put("3951418197004844059", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "autorization"));
    pvqMethods.put("3951418197004662895", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "id"));
    pvqMethods.put("3951418197004657052", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "text"));
    pvqMethods.put("3951418197004660662", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "text"));
    pvqMethods.put("3951418197004644550", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "map_Policy"));
  }
  @NotNull
  @Override
  public PropertyValueQuery getPropertyValueQuery(@NotNull QueryKey identity) {
    PropertyValueQuery query = identity.forTemplateNode(pvqMethods);
    return (query != null ? query : super.getPropertyValueQuery(identity));
  }
  private static class PVQ extends PropertyValueQuery.Base {
    private final int methodKey;
    /*package*/ PVQ(int methodKey, SProperty property, String templateValue) {
      super(property, templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull PropertyMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.propertyMacro_GetValue_1_0(ctx);
        case 1:
          return QueriesGenerated.propertyMacro_GetValue_1_1(ctx);
        case 2:
          return QueriesGenerated.propertyMacro_GetValue_1_2(ctx);
        case 3:
          return QueriesGenerated.propertyMacro_GetValue_1_3(ctx);
        case 4:
          return QueriesGenerated.propertyMacro_GetValue_1_4(ctx);
        case 5:
          return QueriesGenerated.propertyMacro_GetValue_1_5(ctx);
        case 6:
          return QueriesGenerated.propertyMacro_GetValue_1_6(ctx);
        case 7:
          return QueriesGenerated.propertyMacro_GetValue_1_7(ctx);
        case 8:
          return QueriesGenerated.propertyMacro_GetValue_1_8(ctx);
        case 9:
          return QueriesGenerated.propertyMacro_GetValue_1_9(ctx);
        case 10:
          return QueriesGenerated.propertyMacro_GetValue_1_10(ctx);
        case 11:
          return QueriesGenerated.propertyMacro_GetValue_1_11(ctx);
        case 12:
          return QueriesGenerated.propertyMacro_GetValue_1_12(ctx);
        case 13:
          return QueriesGenerated.propertyMacro_GetValue_1_13(ctx);
        case 14:
          return QueriesGenerated.propertyMacro_GetValue_1_14(ctx);
        case 15:
          return QueriesGenerated.propertyMacro_GetValue_1_15(ctx);
        case 16:
          return QueriesGenerated.propertyMacro_GetValue_1_16(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty matchId$v8bY = MetaAdapterFactory.getProperty(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276d54beL, 0x36d641ea276d5835L, "matchId");
    /*package*/ static final SProperty dataType$nnY = MetaAdapterFactory.getProperty(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276c3402L, 0x36d641ea276c3fcfL, "dataType");
    /*package*/ static final SProperty attributeid$Xd30 = MetaAdapterFactory.getProperty(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276c516aL, 0x36d641ea276c643aL, "attributeid");
    /*package*/ static final SProperty catogory$cvsA = MetaAdapterFactory.getProperty(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276c516aL, 0x36d641ea276c5ff4L, "catogory");
    /*package*/ static final SProperty dataType$B160 = MetaAdapterFactory.getProperty(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276c516aL, 0x36d641ea276c67cbL, "dataType");
    /*package*/ static final SProperty mustBePresent$a_mo = MetaAdapterFactory.getProperty(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276c516aL, 0x36d641ea276c6adbL, "mustBePresent");
    /*package*/ static final SProperty ruleid$paNZ = MetaAdapterFactory.getProperty(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276b8152L, 0x36d641ea276bd83cL, "ruleid");
    /*package*/ static final SProperty functionId$J5WM = MetaAdapterFactory.getProperty(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276ba405L, 0x36d641ea276c26e1L, "functionId");
    /*package*/ static final SProperty policyid$TmVT = MetaAdapterFactory.getProperty(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276b7ddbL, 0x36d641ea276c02f0L, "policyid");
    /*package*/ static final SProperty ruleCombiningAlgId$rL3l = MetaAdapterFactory.getProperty(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276b7ddbL, 0x36d641ea276c0596L, "ruleCombiningAlgId");
    /*package*/ static final SProperty version$mVA$ = MetaAdapterFactory.getProperty(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276b7ddbL, 0x36d641ea277a1964L, "version");
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink attrV$AmLZ = MetaAdapterFactory.getReferenceLink(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276d54beL, 0x36d641ea2782cbdfL, "attrV");
    /*package*/ static final SReferenceLink designV$FJoi = MetaAdapterFactory.getReferenceLink(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276d54beL, 0x36d641ea2782d15dL, "designV");
    /*package*/ static final SContainmentLink match$C54c = MetaAdapterFactory.getContainmentLink(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276d4f25L, 0x36d641ea276d5fdbL, "match");
    /*package*/ static final SContainmentLink allof$n99Y = MetaAdapterFactory.getContainmentLink(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276d479dL, 0x6b6bcd963e1010b2L, "allof");
    /*package*/ static final SContainmentLink anyof$6O2d = MetaAdapterFactory.getContainmentLink(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276b9907L, 0x36d641ea276d3f95L, "anyof");
    /*package*/ static final SContainmentLink attributeValue$t8Ga = MetaAdapterFactory.getContainmentLink(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276ba405L, 0x36d641ea276c2f87L, "attributeValue");
    /*package*/ static final SContainmentLink designator$NOtP = MetaAdapterFactory.getContainmentLink(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276ba405L, 0x36d641ea277e0521L, "designator");
    /*package*/ static final SContainmentLink apply$dHjv = MetaAdapterFactory.getContainmentLink(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276b9e1eL, 0x36d641ea276c1db9L, "apply");
    /*package*/ static final SContainmentLink condition$Kgk = MetaAdapterFactory.getContainmentLink(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276b8152L, 0x36d641ea276bf154L, "condition");
    /*package*/ static final SContainmentLink rules$A0S = MetaAdapterFactory.getContainmentLink(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276b7ddbL, 0x36d641ea276b9250L, "rules");
  }
}
