package HOBACITv2.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAction = createDescriptorForAction();
  /*package*/ final ConceptDescriptor myConceptActionType = createDescriptorForActionType();
  /*package*/ final ConceptDescriptor myConceptAllOf = createDescriptorForAllOf();
  /*package*/ final ConceptDescriptor myConceptAnyOf = createDescriptorForAnyOf();
  /*package*/ final ConceptDescriptor myConceptApply = createDescriptorForApply();
  /*package*/ final ConceptDescriptor myConceptAttributeAssignment = createDescriptorForAttributeAssignment();
  /*package*/ final ConceptDescriptor myConceptAttributeDesignator = createDescriptorForAttributeDesignator();
  /*package*/ final ConceptDescriptor myConceptAttributeValue = createDescriptorForAttributeValue();
  /*package*/ final ConceptDescriptor myConceptCondition = createDescriptorForCondition();
  /*package*/ final ConceptDescriptor myConceptEnvironment = createDescriptorForEnvironment();
  /*package*/ final ConceptDescriptor myConceptEnvironmentType = createDescriptorForEnvironmentType();
  /*package*/ final ConceptDescriptor myConceptFunction = createDescriptorForFunction();
  /*package*/ final ConceptDescriptor myConceptMatch = createDescriptorForMatch();
  /*package*/ final ConceptDescriptor myConceptPolicy = createDescriptorForPolicy();
  /*package*/ final ConceptDescriptor myConceptPolicySet = createDescriptorForPolicySet();
  /*package*/ final ConceptDescriptor myConceptResource = createDescriptorForResource();
  /*package*/ final ConceptDescriptor myConceptResourceType = createDescriptorForResourceType();
  /*package*/ final ConceptDescriptor myConceptRule = createDescriptorForRule();
  /*package*/ final ConceptDescriptor myConceptSubject = createDescriptorForSubject();
  /*package*/ final ConceptDescriptor myConceptSubjectType = createDescriptorForSubjectType();
  /*package*/ final ConceptDescriptor myConceptTarget = createDescriptorForTarget();
  /*package*/ final EnumerationDescriptor myEnumerationEffect = new EnumerationDescriptor_Effect();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.aggregatedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAction, myConceptActionType, myConceptAllOf, myConceptAnyOf, myConceptApply, myConceptAttributeAssignment, myConceptAttributeDesignator, myConceptAttributeValue, myConceptCondition, myConceptEnvironment, myConceptEnvironmentType, myConceptFunction, myConceptMatch, myConceptPolicy, myConceptPolicySet, myConceptResource, myConceptResourceType, myConceptRule, myConceptSubject, myConceptSubjectType, myConceptTarget);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Action:
        return myConceptAction;
      case LanguageConceptSwitch.ActionType:
        return myConceptActionType;
      case LanguageConceptSwitch.AllOf:
        return myConceptAllOf;
      case LanguageConceptSwitch.AnyOf:
        return myConceptAnyOf;
      case LanguageConceptSwitch.Apply:
        return myConceptApply;
      case LanguageConceptSwitch.AttributeAssignment:
        return myConceptAttributeAssignment;
      case LanguageConceptSwitch.AttributeDesignator:
        return myConceptAttributeDesignator;
      case LanguageConceptSwitch.AttributeValue:
        return myConceptAttributeValue;
      case LanguageConceptSwitch.Condition:
        return myConceptCondition;
      case LanguageConceptSwitch.Environment:
        return myConceptEnvironment;
      case LanguageConceptSwitch.EnvironmentType:
        return myConceptEnvironmentType;
      case LanguageConceptSwitch.Function:
        return myConceptFunction;
      case LanguageConceptSwitch.Match:
        return myConceptMatch;
      case LanguageConceptSwitch.Policy:
        return myConceptPolicy;
      case LanguageConceptSwitch.PolicySet:
        return myConceptPolicySet;
      case LanguageConceptSwitch.Resource:
        return myConceptResource;
      case LanguageConceptSwitch.ResourceType:
        return myConceptResourceType;
      case LanguageConceptSwitch.Rule:
        return myConceptRule;
      case LanguageConceptSwitch.Subject:
        return myConceptSubject;
      case LanguageConceptSwitch.SubjectType:
        return myConceptSubjectType;
      case LanguageConceptSwitch.Target:
        return myConceptTarget;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationEffect);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "Action", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276bb406L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003711494");
    b.version(3);
    b.property("action_id", 0x36d641ea276ca9ffL).type(PrimitiveTypeId.STRING).origin("3951418197003774463").done();
    b.associate("action_type", 0x36d641ea276cb1a6L).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276cb6f0L).optional(false).origin("3951418197003776422").done();
    b.aggregate("attributes", 0x36d641ea276d24b0L).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x47bf8397520e5939L).optional(true).ordered(true).multiple(true).origin("3951418197003805872").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForActionType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "ActionType", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276cb6f0L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003777776");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAllOf() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "AllOf", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276d4f25L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003816741");
    b.version(3);
    b.property("value", 0x36d641ea278264b8L).type(PrimitiveTypeId.STRING).origin("3951418197005198520").done();
    b.aggregate("match", 0x36d641ea276d5fdbL).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276d54beL).optional(true).ordered(true).multiple(true).origin("3951418197003821019").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAnyOf() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "AnyOf", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276d479dL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003814813");
    b.version(3);
    b.property("value", 0x36d641ea27825f3aL).type(PrimitiveTypeId.STRING).origin("3951418197005197114").done();
    b.aggregate("allof", 0x6b6bcd963e1010b2L).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276d4f25L).optional(false).ordered(true).multiple(true).origin("7740506429736358066").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForApply() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "Apply", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276ba405L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003707397");
    b.version(3);
    b.property("functionId", 0x36d641ea276c26e1L).type(PrimitiveTypeId.STRING).origin("3951418197003740897").done();
    b.aggregate("attributeValue", 0x36d641ea276c2f87L).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276c3402L).optional(true).ordered(true).multiple(true).origin("3951418197003743111").done();
    b.aggregate("designator", 0x36d641ea277e0521L).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276c516aL).optional(true).ordered(true).multiple(true).origin("3951418197004911905").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAttributeAssignment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "AttributeAssignment", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276d6baaL);
    b.class_(false, false, false);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003824042");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAttributeDesignator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "AttributeDesignator", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276c516aL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003751786");
    b.version(3);
    b.property("catogory", 0x36d641ea276c5ff4L).type(PrimitiveTypeId.STRING).origin("3951418197003755508").done();
    b.property("attributeid", 0x36d641ea276c643aL).type(PrimitiveTypeId.STRING).origin("3951418197003756602").done();
    b.property("dataType", 0x36d641ea276c67cbL).type(PrimitiveTypeId.STRING).origin("3951418197003757515").done();
    b.property("mustBePresent", 0x36d641ea276c6adbL).type(PrimitiveTypeId.BOOLEAN).origin("3951418197003758299").done();
    b.associate("attributevalue", 0x36d641ea27767a28L).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276c3402L).optional(false).origin("3951418197004417576").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAttributeValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "AttributeValue", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276c3402L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003744258");
    b.version(3);
    b.property("attributeId", 0x36d641ea276c3ad3L).type(PrimitiveTypeId.STRING).origin("3951418197003746003").done();
    b.property("dataType", 0x36d641ea276c3fcfL).type(PrimitiveTypeId.STRING).origin("3951418197003747279").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCondition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "Condition", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276b9e1eL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003705886");
    b.version(3);
    b.property("conditionId", 0x36d641ea276c1aabL).type(PrimitiveTypeId.STRING).origin("3951418197003737771").done();
    b.aggregate("apply", 0x36d641ea276c1db9L).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276ba405L).optional(true).ordered(true).multiple(true).origin("3951418197003738553").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEnvironment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "Environment", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276bc97cL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003716988");
    b.version(3);
    b.property("environment_id", 0x36d641ea276ceda9L).type(PrimitiveTypeId.STRING).origin("3951418197003791785").done();
    b.associate("type", 0x36d641ea276cf272L).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276cfab1L).optional(false).origin("3951418197003793010").done();
    b.aggregate("attributes", 0x36d641ea276d0fe2L).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x47bf8397520e5939L).optional(true).ordered(true).multiple(true).origin("3951418197003800546").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEnvironmentType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "EnvironmentType", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276cfab1L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003795121");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFunction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "Function", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276d665eL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003822686");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMatch() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "Match", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276d54beL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003818174");
    b.version(3);
    b.property("matchId", 0x36d641ea276d5835L).type(PrimitiveTypeId.STRING).origin("3951418197003819061").done();
    b.associate("attrV", 0x36d641ea2782cbdfL).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276c3402L).optional(false).origin("3951418197005224927").done();
    b.associate("designV", 0x36d641ea2782d15dL).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276c516aL).optional(false).origin("3951418197005226333").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPolicy() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "Policy", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276b7ddbL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003697627");
    b.version(3);
    b.property("policyid", 0x36d641ea276c02f0L).type(PrimitiveTypeId.STRING).origin("3951418197003731696").done();
    b.property("ruleCombiningAlgId", 0x36d641ea276c0596L).type(PrimitiveTypeId.STRING).origin("3951418197003732374").done();
    b.property("maxDelegationDepth", 0x36d641ea276c0b7dL).type(PrimitiveTypeId.STRING).origin("3951418197003733885").done();
    b.property("description", 0x36d641ea276c0f77L).type(PrimitiveTypeId.STRING).origin("3951418197003734903").done();
    b.property("version", 0x36d641ea277a1964L).type(PrimitiveTypeId.STRING).origin("3951418197004654948").done();
    b.associate("target", 0x36d641ea27861fe5L).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276b9907L).optional(false).origin("3951418197005443045").done();
    b.aggregate("rules", 0x36d641ea276b9250L).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276b8152L).optional(false).ordered(true).multiple(true).origin("3951418197003702864").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPolicySet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "PolicySet", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276b77f4L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003696116");
    b.version(3);
    b.aggregate("policy", 0x36d641ea276b8604L).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276b7ddbL).optional(true).ordered(true).multiple(true).origin("3951418197003699716").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForResource() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "Resource", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276baf08L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003710216");
    b.version(3);
    b.property("resource_id", 0x36d641ea276cc680L).type(PrimitiveTypeId.STRING).origin("3951418197003781760").done();
    b.associate("type", 0x36d641ea276cd0fcL).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276cde66L).optional(false).origin("3951418197003784444").done();
    b.aggregate("attributes", 0x36d641ea276d1bd4L).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x47bf8397520e5939L).optional(true).ordered(true).multiple(true).origin("3951418197003803604").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForResourceType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "ResourceType", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276cde66L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003787878");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRule() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "Rule", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276b8152L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003698514");
    b.version(3);
    b.property("ruleid", 0x36d641ea276bd83cL).type(PrimitiveTypeId.STRING).origin("3951418197003720764").done();
    b.property("effect", 0x36d641ea276bda46L).type(MetaIdFactory.dataTypeId(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276bdf77L)).origin("3951418197003721286").done();
    b.aggregate("condition", 0x36d641ea276bf154L).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276b9e1eL).optional(true).ordered(true).multiple(true).origin("3951418197003727188").done();
    b.aggregate("target", 0x36d641ea276bf5b4L).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276b9907L).optional(false).ordered(true).multiple(false).origin("3951418197003728308").done();
    b.aggregate("apply", 0x36d641ea2782bd5eL).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276ba405L).optional(true).ordered(true).multiple(true).origin("3951418197005221214").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSubject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "Subject", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276ba96bL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003708779");
    b.version(3);
    b.property("subject_id", 0x36d641ea276c81f0L).type(PrimitiveTypeId.STRING).origin("3951418197003764208").done();
    b.associate("subject_type", 0x36d641ea276c8ceaL).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276c95dcL).optional(false).origin("3951418197003767018").done();
    b.aggregate("attributes", 0x36d641ea276d2d24L).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x47bf8397520e5939L).optional(true).ordered(true).multiple(true).origin("3951418197003808036").done();
    b.alias("sujet");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSubjectType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "SubjectType", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276c95dcL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003769308");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTarget() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HOBACITv2", "Target", 0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276b9907L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b50a6759-538a-42a4-9677-fc7bf90835ec(HOBACITv2.structure)/3951418197003704583");
    b.version(3);
    b.aggregate("anyof", 0x36d641ea276d3f95L).target(0x3fbb45ee81da477eL, 0xba7df1b8ec591273L, 0x36d641ea276d479dL).optional(false).ordered(true).multiple(true).origin("3951418197003812757").done();
    return b.create();
  }
}
